use crate::config::Config;
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::process::Command;


pub fn uninstall(config: &Config) {
    let toggle_path = config.dir.join("toggle.sh");

    // Remove toggle.sh
    if toggle_path.exists() {
        match fs::remove_file(&toggle_path) {
            Ok(_) => println!("tnote: removed {}", toggle_path.display()),
            Err(e) => eprintln!("tnote: failed to remove {}: {}", toggle_path.display(), e),
        }
    } else {
        println!("tnote: {} not found, skipping", toggle_path.display());
    }

    // Overwrite tmux.conf with empty content and re-source to drop the bindings
    let tmux_conf_path = config.dir.join("tmux.conf");
    let cleared = "# tnote key bindings — cleared by 'tnote uninstall'\n";
    match fs::write(&tmux_conf_path, cleared) {
        Ok(_) => {
            let _ = Command::new("tmux")
                .args(["source-file", &tmux_conf_path.to_string_lossy()])
                .status();
            println!("tnote: cleared bindings from live tmux session");
        }
        Err(_) => {
            // File didn't exist — fall back to manual unbind
            let _ = Command::new("tmux").args(["unbind-key", "C-n"]).status();
        }
    }

    println!("tnote: uninstall complete.");
    println!("tnote: if you added source-file to ~/.tmux.conf, you can remove that line now:");
}

pub fn run(config: &Config) {
    // 1. Ensure the notes directory exists
    if let Err(e) = fs::create_dir_all(&config.dir) {
        eprintln!("tnote: failed to create {}: {}", config.dir.display(), e);
        std::process::exit(1);
    }

    // 2. Write toggle.sh
    let toggle_path = config.dir.join("toggle.sh");
    let script = r#"#!/usr/bin/env bash
# tnote toggle script — generated by 'tnote install'
# Bound to Ctrl+N via: tmux bind-key -n C-n run-shell ~/.tnotes/toggle.sh
exec tnote
"#;

    if let Err(e) = fs::write(&toggle_path, script) {
        eprintln!("tnote: failed to write {}: {}", toggle_path.display(), e);
        std::process::exit(1);
    }

    // Make it executable (chmod +x)
    if let Err(e) = fs::set_permissions(&toggle_path, fs::Permissions::from_mode(0o755)) {
        eprintln!("tnote: failed to chmod {}: {}", toggle_path.display(), e);
        std::process::exit(1);
    }

    println!("tnote: wrote {}", toggle_path.display());

    // 3. Write ~/.tnotes/tmux.conf with the key bindings
    let toggle_str = toggle_path.to_string_lossy().into_owned();
    let tmux_conf_path = config.dir.join("tmux.conf");
    // The popup binding uses send-keys directly (editor-specific) rather than run-shell,
    // because tmux popup only routes keys through the popup key table when opened with -K,
    // and send-keys targets the popup pane reliably from that context.
    let tmux_conf = format!(
        "# tnote key bindings — managed by 'tnote install' / 'tnote uninstall'\n\
         # Uses the tmux prefix key (adapts automatically if you change prefix).\n\
         bind-key C-n run-shell {toggle_str}\n"
    );

    if let Err(e) = fs::write(&tmux_conf_path, &tmux_conf) {
        eprintln!("tnote: failed to write {}: {}", tmux_conf_path.display(), e);
        std::process::exit(1);
    }
    println!("tnote: wrote {}", tmux_conf_path.display());

    // 4. Source it into the live tmux session
    let status = Command::new("tmux")
        .args(["source-file", &tmux_conf_path.to_string_lossy()])
        .status();

    match status {
        Ok(s) if s.success() => {
            println!("tnote: sourced bindings into live tmux session");
        }
        Ok(_) => {
            eprintln!("tnote: tmux source-file failed (is tmux running?)");
            std::process::exit(1);
        }
        Err(e) => {
            eprintln!("tnote: could not run tmux: {}", e);
            std::process::exit(1);
        }
    }

    println!("tnote: install complete. Binding: <prefix> C-n");
    println!("tnote: to persist across tmux restarts, add this one line to ~/.tmux.conf:");
    println!("         source-file {}", tmux_conf_path.display());
}
